Configure versioneer.
neutrons/RefRed pull request #13
Opened 2021-09-20 19:58 UTC by wdzhou

Configure versioneer to fix ORNL task [#110](https://code.ornl.gov/sns-hfir-scse/reflectometry/reflectometry/-/issues/110)

2021-09-20 20:33 UTC, jmborr requested changes

2021-09-20 20:33 UTC, jmborr commented on _version.py
> +    cfg.versionfile_source = "datsans/_version.py"
change `datsans` to `RefRed`

2021-09-20 20:33 UTC, jmborr commented on setup.cfg
> +versionfile_source = drtsans/_version.py
change `drtsans` to `RefRed`

2021-09-20 20:35 UTC, jmborr commented
@wdzhou After you make these two little changes, go ahead and merge the PR yourself if you want to

2021-09-20 23:56 UTC, wdzhou commented on _version.py
> +    cfg.versionfile_source = "datsans/_version.py"
Done!

2021-09-21 00:01 UTC, wdzhou commented
@jmborr Can you review again?  I don't have the permission to merge.

2021-09-21 00:08 UTC, merged