Ignore files created by versioneer
neutrons/RefRed pull request #56
Opened 2021-10-29 20:36 UTC by peterfpeterson

2021-11-02 17:36 UTC, rosswhitfield requested changes
How about configuring coverage instead of codecov, that way when a developer runs the code coverage locally they will get the same results as codecov.

Just add
```
[coverage:report]
omit =
    versioneer.py
    RefRed/_version.py
```

to `setup.cfg`

2021-11-03 12:53 UTC, peterfpeterson commented
For some reason this PR doesn't generate a difference report and I can't figure out why. I'm happy to change tools, but [coverage](https://coverage.readthedocs.io/en/6.1.1/) doesn't appear to have the nice report on the web for people to look at.

2021-11-03 12:56 UTC, rosswhitfield commented
> For some reason this PR doesn't generate a difference report and I can't figure out why. I'm happy to change tools, but [coverage](https://coverage.readthedocs.io/en/6.1.1/) doesn't appear to have the nice report on the web for people to look at.

coverage is the tool we are running to calculate the code coverage, when you add `--cov` to `pytest` it runs `coverage`, the results of which are sent to codecov.

2021-11-03 13:08 UTC, rosswhitfield approved these changes

2021-11-03 13:11 UTC, merged